name: expence_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  cupertino_icons: ^1.0.8
  firebase_core: 4.2.1
  firebase_auth: 6.1.2
  cloud_firestore: 6.1.0
  firebase_storage: ^13.0.4
  image_picker: ^1.2.1
  lottie: ^3.3.1
  razorpay_flutter: ^1.3.5
  mobile_scanner: ^7.1.4
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  firebase_ai: ^3.6.0
  flutter_ai_toolkit: ^0.10.0
  flutter_ai_chatbot: ^0.0.3
  http: ^1.6.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  pdf: ^3.11.3
  printing: ^5.14.2
  syncfusion_flutter_xlsio: ^31.1.19
  path_provider: ^2.1.5
  firebase_messaging: ^16.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Recommended lints for good coding practices

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/expense_splash.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Icons/AppIcons/budget_9165700.png"
  remove_alpha_ios: true


fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700


